#!/bin/sh

#if [ $# -ne 1 ] ;then
#	echo "Need ip";
#	exit;
#fi

#sshpass -p 'f2a0n0w8a0r6e' ssh $1 "pkill ica"

sshpass -p 'f2a0n0w8a0r6e' scp /root/linux/linux/vclient-build-desktop-Debug/vClient 192.168.20.5:/opt/vclient

#sshpass -p 'f2a0n0w8a0r6e' scp /usr/local/lib/libItalcCore.so $1:/usr/lib/

#sshpass -p 'f2a0n0w8a0r6e' ssh $1 reboot
