#!/bin/sh
set -x
PKG_NAME=vclient
SRC_DIR=~/rpmbuild/SOURCES
RELEASE=1
VERSION=2.9.2.72

rsync -a `pwd`/* $SRC_DIR/$PKG_NAME-$VERSION 
cd $SRC_DIR
tar zcvf $SRC_DIR/$PKG_NAME-$VERSION.tar.gz $PKG_NAME-$VERSION --exclude .svn
rm -rf $SRC_DIR/$PKG_NAME-$VERSION
cd -
rpmbuild -ba $PKG_NAME.spec -D "RELEASE ${RELEASE}" -D "VERSION ${VERSION}"
mv -f ~/rpmbuild/RPMS/$(uname -p)/$PKG_NAME-$VERSION*-${RELEASE}.fc20.$(uname -p).rpm rpm/
